// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJt-Sv8hOJmdXveujA5k5I3GSwO1jsIgc',
    appId: '1:753570206235:web:db911c45cfbef674151ebe',
    messagingSenderId: '753570206235',
    projectId: 'anuncios-aa82d',
    authDomain: 'anuncios-aa82d.firebaseapp.com',
    storageBucket: 'anuncios-aa82d.appspot.com',
    measurementId: 'G-SLXDXG97W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzoKzeBYK1wHxsatOe_uHkHhf28_43-Q',
    appId: '1:753570206235:android:03bd9ba71919eda0151ebe',
    messagingSenderId: '753570206235',
    projectId: 'anuncios-aa82d',
    storageBucket: 'anuncios-aa82d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl5CiDHZRKh5hw0VSVMIkcvia96IaiOKU',
    appId: '1:753570206235:ios:a6afd579e9d2feed151ebe',
    messagingSenderId: '753570206235',
    projectId: 'anuncios-aa82d',
    storageBucket: 'anuncios-aa82d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl5CiDHZRKh5hw0VSVMIkcvia96IaiOKU',
    appId: '1:753570206235:ios:a6afd579e9d2feed151ebe',
    messagingSenderId: '753570206235',
    projectId: 'anuncios-aa82d',
    storageBucket: 'anuncios-aa82d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJt-Sv8hOJmdXveujA5k5I3GSwO1jsIgc',
    appId: '1:753570206235:web:50fc602978db5305151ebe',
    messagingSenderId: '753570206235',
    projectId: 'anuncios-aa82d',
    authDomain: 'anuncios-aa82d.firebaseapp.com',
    storageBucket: 'anuncios-aa82d.appspot.com',
    measurementId: 'G-6T89MXS1MP',
  );

}