// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD9bf5g3qS34VbjIEtGi_7hxB5WtN0-k0',
    appId: '1:1094119926815:web:28e6da7fc3d8d9f00f392a',
    messagingSenderId: '1094119926815',
    projectId: 'anuncios-49fb0',
    authDomain: 'anuncios-49fb0.firebaseapp.com',
    storageBucket: 'anuncios-49fb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJyHB5uptuDwuLp2yMsLl9xJDmhWTpzaw',
    appId: '1:1094119926815:android:6dedba8ea22ebddf0f392a',
    messagingSenderId: '1094119926815',
    projectId: 'anuncios-49fb0',
    storageBucket: 'anuncios-49fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwES9uR9n0j9-gTyj7YuF-KTt5DtOgc0Y',
    appId: '1:1094119926815:ios:03478b8e7196f64b0f392a',
    messagingSenderId: '1094119926815',
    projectId: 'anuncios-49fb0',
    storageBucket: 'anuncios-49fb0.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwES9uR9n0j9-gTyj7YuF-KTt5DtOgc0Y',
    appId: '1:1094119926815:ios:03478b8e7196f64b0f392a',
    messagingSenderId: '1094119926815',
    projectId: 'anuncios-49fb0',
    storageBucket: 'anuncios-49fb0.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD9bf5g3qS34VbjIEtGi_7hxB5WtN0-k0',
    appId: '1:1094119926815:web:3465e27761af6e310f392a',
    messagingSenderId: '1094119926815',
    projectId: 'anuncios-49fb0',
    authDomain: 'anuncios-49fb0.firebaseapp.com',
    storageBucket: 'anuncios-49fb0.appspot.com',
  );
}
